-- Testimonials table for Super CTA Responder
create table if not exists testimonials (
  id           uuid primary key default gen_random_uuid(),
  quote        text not null,
  customer_details text,
  case_study_url   text,
  sector       text not null,  -- k12 | higher_edu | vocational | corporate | utilities | museum | manufacturing | ngo
  segment      text not null,  -- education | business
  created_at   timestamptz default now()
);

-- Index for sector lookups
create index if not exists testimonials_sector_idx on testimonials (sector);

-- Data
insert into testimonials (quote, customer_details, case_study_url, sector, segment) values
  (E'“When we talk about Collaborative Learning, Peer Learning and Peer feedback, it’s a fabulous platform…that’s something that all of the Educators and the students rave about!”.', E'Rachel Wolf, Virtual Field Trips project team, Stanford Accelerator for Learning’s Digital Learning Initiative', E'https://www.thinglink.com/blog/empowering-place-based-learning-through-student-creation-with-stanfords-virtual-learning-resources/', 'k12', 'education'),
  (E'“It’s the next frontier of how to make the classroom engaging! We need to immerse students in their learning environments so that they want to be at school.”', E'Joseph D\'Aquila, St. John Henry Newman Catholic High School and the Toronto Catholic District Schools Board', E'https://www.thinglink.com/blog/how-a-toronto-teacher-combines-thinglink-and-ai-to-better-engage-students-in-online-learning/', 'k12', 'education'),
  (E'“I’ve never seen such enthusiasm for a task in any class that I can ever remember. The girls loved it. They all want to do more. Without ThingLink, creating something like this would be impossible. Now that you’ve got SkyBox and DallE3 integrated, my only need to go outside of ThingLink is to generate the text ideas and story line.”', E'Rob McCrae, Teacher, Diocesan School for Girls, Auckland, New Zealand', NULL, 'k12', 'education'),
  (E'“It was a sad day when we had to say goodbye to Google Street View…and a very happy day when ThingLink came to the rescue with Pano to 360!”', E'Amanda Brougham-Pickard, Educator', E'Webinar comments: https://www.youtube.com/watch?v=yEHlsBdwTmE', 'k12', 'education'),
  (E'“So easy, it’s incredible. On the hoof, out and about, whenever I see something that could inspire my kids....ThingLink is phenomenal....So many incredible developments - ThingLink just gets better and better!”', E'Amanda Brougham-Pickard, Educator', E'Webinar comments: https://www.youtube.com/watch?v=tVhACFpxJGQ', 'k12', 'education'),
  (E'“ThingLink is magic. Easy to use and powerful.”', E'Amanda Brougham-Pickard, Educator', E'Webinar comments: https://www.youtube.com/watch?v=GkSi55heVAs', 'k12', 'education'),
  (E'“Our students create digital escape rooms with ThingLink. They really enjoy it!”', E'Dr. Susan Murray, Educational Technology Coordinator, Oak Hill Academy', E'Webinar comment: https://www.youtube.com/watch?v=o2OLx8n_RPA', 'k12', 'education'),
  (E'“It allows us to seamlessly weave together a massive amount of content into a format that is a simple, organized, visually-appealing (one-page!) landing page.', E'Lorrie Salome, Teacher, Austin Independent School District, Texas', E'https://www.thinglink.com/blog/home-learning-designs-to-reduce-confusion-and-increase-engagement/', 'k12', 'education'),
  (E'As we evolved through this process, we were able to make each image a little bit more catered to what we see being used the most...ThingLink has been the best thing that could happen to us!”', E'Lorrie Salome, Teacher, Austin Independent School District, Texas', E'Choice Boards with Austin Independent School (Without Tutorial) - YouTube', 'k12', 'education'),
  (E'This innovative software has multiple learning applications including improving digital literacy and the quality of school and post-school curricula and learning. Through this online tool, learners can virtually access environments beyond their physical reach to develop cultural awareness and engage in experiential learning. ThingLink further empowers learners to create and document their own learning and allows educators to customize lessons to support students with different learning skills.', E'Unesco Report 2021', E'https://unesdoc.unesco.org/ark:/48223/pf0000380189', 'k12', 'education'),
  (E'ThingLink was selected as a laureate due to its:•intuitive software, which is flexible and able to support users’ learning experiences, regardless of educational level,•support of learners’ virtual mobility and offering a creative space for marginalized learners such as those with disabilities or limited ability for expression, •accessibility to educators across formal, informal and community learning environments, •capacity to support interaction between teachers and students who can become producers of openly accessible resources for the ThingLink database (UNESCO, 2018).ThingLink Visual Learning Technology | ThingLink 3ThingLink: An immersive learning tool for accessible quality education', E'Unesco Report 2021', E'https://unesdoc.unesco.org/ark:/48223/pf0000380189', 'k12', 'education'),
  (E'ThingLink is not just a tool. It is a supportive community designed to provide teachers with rich, interactive experiences that engage learners and immerses them into worlds they may not possibly be able to experience otherwise.', E'Laura Moore, classroom teacher , quoted in Unesco Report 2021', E'https://unesdoc.unesco.org/ark:/48223/pf0000380189', 'k12', 'education'),
  (E'ThingLink has provided us with a tool for our students to be creators of authentic and interactive Virtual Reality content!', E'Brian and Jennifer Cauthers, science teachers, quoted in Unesco Report 2021', E'https://unesdoc.unesco.org/ark:/48223/pf0000380189', 'k12', 'education'),
  (E'ThingLink has allowed my students to become the experts by sharing their knowledge with their peers and other classrooms around the world.', E'_Leilani Sills, classroom teacher, quoted in Unesco Report 2021', E'https://unesdoc.unesco.org/ark:/48223/pf0000380189', 'k12', 'education'),
  (E'“If you can think it, you can create it in ThingLink. Everything I’ve ever envisioned, I’ve been able to do with the platform. ThingLink has been a game-changer on the front line of education.”', E'Tyler Counsil, CAST Director', E'https://www.thinglink.com/blog/thinglink-virtual-environments-and-scenarios-enhance-child-protection-training/', 'higher_edu', 'education'),
  (E'“What we loved most about the tool was that you don’t need to be a developer to build tours; you can build engaging interactions really easily. We needed to deploy a tour quickly and easily and ThingLink really helped us do that. It was a quick, easy solution to a really big problem”.', E'Wade Holdraker, AVP - Digital Strategy and Web Operations, University of Rochester Medical Center', E'https://www.thinglink.com/blog/campus-visit-experience/', 'higher_edu', 'education'),
  (E'“The (ThingLink) interface is very intuitive. I find that it’s a great way of conveying a lot of information in a way that people naturally process”.', E'Dr Sarah Fielding, Digital Learning Team Manager, Southampton University', E'https://www.thinglink.com/blog/next-level-field-trips/', 'higher_edu', 'education'),
  (E'“One of the greatest strengths of the ThingLink platform is its simplicity and user-friendliness, allowing users to easily create and disseminate immersive, interactive learning materials with very little training time.”', E'Jeffery et al, Thinglink and the Laboratory, Journal of Chemical Education May 2022 Note: This is one of 3 research papers into the use of ThingLink which provide evidence of efficacy with students. Collated here: Evidence of Impact (linked on Higher Ed landing Page)', E'https://www.thinglink.com/blog/thinglink-evidence-of-impact/', 'higher_edu', 'education'),
  (E'“We wanted to create an interactive Virtual Field Trip for the classroom so that students can visit a site virtually and better prepare themselves for work out in the field.….We discovered that ThingLink was obviously the best platform out there which allowed us to do that quite easily…It’s simple and easy to use and it’s also accessible….This is pretty much the next best thing to actually being there, and there’s even an option to view it in VR…ThingLink makes it really easy for anyone to do. I wouldnt have a clue how to put anything together like this using any other software or package! So far we’ve had a positive response to the interactive map both from academic staff and prospective students. We really think it makes the department stand out and I highly recommend using it. ”', E'Luke Hobson, Technician, School of Geography, Geology and the Environment, Keele University', E'ThingLink Spotlight with Keele University - YouTube', 'higher_edu', 'education'),
  (E'“An innovative way...to stimulate interpersonal skills such as teamwork and communication skills. It also helps us to learn about how a team can operate under stressful situations and what skills we need in order to provide care efficiently.”', E'Learner Feedback to ThingLink Sepsis Escape Room created by Dr Abhi Jones, Clinical Lead for Interprofessional Education, University of Central Lancashire', E'https://www.thinglink.com/blog/med-escaperoom/', 'higher_edu', 'education'),
  (E'“ThingLink has been a fantastic addition to our start-of-term activities, receiving overwhelmingly positive feedback since we launched the escape room in 2022. This success has allowed staff to dedicate more time to students during these busy periods in the academic calendar.”', E'Louise Conway, Information Manager, University of Hertfordshire', E'https://www.thinglink.com/blog/hundreds-of-student-inductions-delivered-with-a-thinglink-virtual-escape-room/', 'higher_edu', 'education'),
  (E'“The whole ThingLink team is amazing. So solutions oriented, and so accessible!! I absolutely love this tool and all that you are doing! It’s incredible to have feedback taken so seriously.”', E'Sarah Dove, Ohio State University', E'Webinar comment https://www.youtube.com/watch?v=GkSi55heVAs', 'higher_edu', 'education'),
  (E'“We have created ThingLinks for our Construction (course) delivery. Great for highlighting hazards without endangering our students.”', E'Kate Whyles, Nottingham College', E'Webinar comment https://www.youtube.com/watch?v=o2OLx8n_RPA', 'higher_edu', 'education'),
  (E'My students LOVE the Immersive Reader - comes up a lot in module reviews.', E'Lisa Gee', E'Webinar comment https://www.youtube.com/watch?v=IlnLwRT-8Ss', 'higher_edu', 'education'),
  (E'You are one of the VERY few platforms that foregrounds accessibility. That\'s why I trust you!', E'Lisa Gee', E'Webinar comment https://www.youtube.com/watch?v=IlnLwRT-8Ss', 'higher_edu', 'education'),
  (E'ThingLink is the best and most easily used software to bring technology into education. I\'m a Learning Technologist and I promote ThingLink more than any other software.', E'Nick Bartlett', E'Webinar comment https://www.youtube.com/watch?v=LAT9BTVfjEg&t=8s', 'higher_edu', 'education'),
  (E'“At The Energy Training Academy, one of our key objectives is to inspire and educate young people about energy efficiency, the path to Net Zero, and the diverse career opportunities within the renewables sector. ThingLink enables us to virtually bring hundreds of schoolchildren into the academy, making our energy efficiency training both engaging and interactive. Through this technology, we aim to make learning about energy exciting and accessible, developing a deeper understanding of the urgent need for a transition to a Net Zero future.”', E'Andrew Lamond, Director, Energy Training Academy', E'https://www.thinglink.com/blog/virtual-tour-of-facilities-brings-learners-to-the-energy-training-academy/', 'vocational', 'education'),
  (E'“ThingLink Scenario Builder allows for rapid mapping of scenarios in multiple formats and situations; creating diverse situations with corresponding results was seamless. The end-of-scenario summary allows learners to receive feedback in the moment.”', E'Jason O’Brien, Manager of Instructional Design, Global Retail Learning, New York - Tiffany & Co', E'n/a', 'corporate', 'business'),
  (E'ThingLink has been seen as a very good tool - today\'s application improves security and makes navigating the substations much easier.', E'Veijo Siiankoski, Fingrid - Finland’s national electricity grid', E'https://www.thinglink.com/blog/cost-effective-carbon-efficient-and-safe-inductions/', 'utilities', 'business'),
  (E'“It’s much easier for staff to go into the field with this kind of support. You can be confident that that person is doing their job correctly.”', E'Patryk Wojtowicz, Smart Water Group, Savonia UAS', E'thinglink.com/blog/thinglinks-new-ar-app-helps-keep-water-flowing', 'utilities', 'business'),
  (E'“In this situation there wouldn’t be any better way to represent this educationally.”', E'Heini Snellman, Environmental Specialist at HSY (Helsinki Region Environmental Services Authority)', E'thinglink.com/blog/hsy-partners-with-thinglink/ Virtual tour of water treatment facility', 'utilities', 'business'),
  (E'“It shows ThingLink’s ease of use that we haven’t needed to do any staff training on it. It’s so intuitive. It’s very, very user friendly”.', E'Julie Muir, Learning Manager, V&A Dundee', E'https://www.thinglink.com/blog/va-dundee-widens-access-with-thinglink/', 'museum', 'business'),
  (E'“Pinterest for the 21st century. It puts more of our content in one place – helping to streamline focus. It provides a broad picture – but you can dive into the parts that you want to and you can step back easily too. It provides the different levels that different learners need.”', E'Julie Muir, Learning Manager, V&A Dundee', E'https://www.thinglink.com/blog/va-dundee-widens-access-with-thinglink/', 'museum', 'business'),
  (E'“ThingLink has been a GAME CHANGER for both our programs and our Professional Development. It’s so responsive – we can update it ourselves in 30 seconds. It’s able to change and adapt as we do”.', E'Royal Ontario Museum, Toronto', E'https://www.thinglink.com/blog/roms-virtual-tours-solve-access-issues/', 'museum', 'business'),
  (E'“ThingLink just keeps getting better and better. Not the usual experience from other vendors. Great work and keep up the innovation.”', E'Webinar attendee from heritage sector', E'Webinar comment: https://www.youtube.com/watch?v=GkSi55heVAs', 'museum', 'business'),
  (E'“ThingLink matches our technological expertise in our field. We need to show that we are thought leaders in our space – that we know how to create and apply intelligent systems to solve problems. This goes hand in hand with using ThingLink to demonstrate these solutions.”', E'Dakota Hoeppner, Marketing Communications Specialist, Carmanah, leading manufacturer of systems for traffic safety with thousands of installations across North America.', E'https://www.thinglink.com/blog/multi-use-interactive-content-trade-shows-website/', 'manufacturing', 'business'),
  (E'“It was invaluable to be able to place the product in context for our stand visitors rather than see it on its own. They were totally immersed by the content as we took them into various parts of the tour.”', E'Business Development Team, Carmanah - leading manufacturer of systems for traffic safety with thousands of installations across North America.', E'https://www.thinglink.com/blog/multi-use-interactive-content-trade-shows-website/', 'manufacturing', 'business'),
  (E'“ThingLink content is easy to create, and easy to use.”', E'KAESER, one of the world’s leading manufacturers of compressed air products', E'thinglink.com/blog/kaesers-360-virtual-tours-provide-a-unique-way-for-customers-to-explore-products-remotely/', 'manufacturing', 'business'),
  (E'“Hand on heart – ThingLink has been a joy to work with as it’s so straightforward to figure out.”', E'MITSUBISHI ELECTRIC UK Steve Clark, Technical Trainer, MEUK', E'https://www.thinglink.com/blog/how-mitsubishi-electric-is-creating-innovative-vr-training-with-thinglink/', 'manufacturing', 'business'),
  (E'“The great thing about the VR content on ThingLink is that it doesn’t HAVE to be viewed through a VR headset. Those who prefer a computer or simply don’t have a VR headset, can still appreciate this content.”', E'MITSUBISHI ELECTRIC UK Steve Clark, Technical Trainer, MEUK', NULL, 'manufacturing', 'business'),
  (E'“Using a combination of real-life 360 and 3D content with interactive simulation scenarios, ThingLink and 3D Talo have developed much more realistic training materials than our employees have seen before. Because we now have training in 11 languages, we’re able to let employees in all our global locations experience just what it feels like to operate the forklift – without putting them or anyone else in danger. Employees enjoy the training and that’s reflected in higher engagement and completion rates.”', E'Jolanta – Safety Manager, Stora Enso - one of the world\'s oldest companies', E'https://www.thinglink.com/blog/innovative-vr-safety-training-at-stora-enso-with-thinglink-and-meta-quest/', 'manufacturing', 'business'),
  (E'“The amount of time that people were spending on this interactive map was far more than they would spend on a typical piece on the website. The analytics showed that people who were clicking on it were really engaged with it and spending a long time on it.”', E'Philippa Gerrand, Journalist, Press & Journal', E'https://www.thinglink.com/blog/interactive-audio-map/', 'manufacturing', 'business'),
  (E'“ThingLink provides turnkey, mobile-friendly and technologically advanced visualization tools.”', E'Nicolas Becquet, Award-winning Journalist, L’Echo (Belgium)', E'https://www.thinglink.com/blog/lecho-multimedia-journalism-thinglink/', 'manufacturing', 'business'),
  (E'For any company that comes from a traditional print background, ThingLink really hits the sweet spot for quickly turning many print graphics into interactive graphics for their digital audience.', E'Michael Hogue, Art Director at Dallas News', E'https://www.thinglink.com/blog/360-image-case-study-the-dallas-morning-news/', 'manufacturing', 'business'),
  (E'ThingLink delivers an immersive online experience for our supporters, so that they can meet the residents of Tombohuaun, Sierra Leone, and explore what life is like there.', E'Digital Content and Experience Lead at WaterAid, Alicia Robinson', E'https://www.thinglink.com/blog/interactive-360-experience-wateraid/', 'ngo', 'business'),
  (E'“ThingLink has been a great platform for both myself and learners whilst accessing the Castle Campbell case study via Moodle. There is a huge benefit to my learners as the case study developed and layout is very similar to the course each learner is undertaking – Planning, Surveying, and Recording the Condition of Built Assets for Conservation (SAC8). The ThingLink platform is simple and effortless to navigate and is now a big part of my course overall including in class assessments and online learning.”', E'Jack Lawson, Training Manager, Historic Environment Scotland', E'coming soon', 'ngo', 'business');